### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kehiy** [aka-deVOID/twitter-tools#1]
I think its good to add some document or example file to project that explain how they can use this project!

**Comment by aka-deVOID** [comment]
the project has a CLI interface. but I add some examples in the README file.

**Comment by kehiy** [comment]
nice, if you wish you can assign it to me.

**Comment by aka-deVOID** [comment]
> nice, if you wish you can assign it to me.

Open to PR ... but I need to write some base code.
